### ISSUE TITLE
script.js page issue 

### ISSUE THREAD

**Issue by gitachyut** [akdekagit/new_test#2]
script.js page still not linked to index.html page and it's still empty .. plz check @akdekagit

**Comment by akdekagit** [comment]
Ok @gitachyut , I will fix it

**Comment by akdekagit** [comment]
@gitachyut issue fixed #2

**Comment by akdekagit** [comment]
close #2

**Comment by akdekagit** [comment]
close #1

**Comment by akdekagit** [comment]
Fixes #2

**Comment by gitachyut** [comment]
Fixes #2
